In [11]:
import numpy as np
import pandas as pd

In [2]:
a = [1,2,3]
b = [4,5,6]

In [3]:
a+b

[1, 2, 3, 4, 5, 6]

In [5]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [12]:
c = a+b

In [13]:
c

array([5, 7, 9])

In [35]:
df = pd.DataFrame({
    'a' : [1,2,3],
    'b' : [4,5,6],
    'c' : [7,8,9]
})

In [36]:
df

a  b  c
0  1  4  7
1  2  5  8
2  3  6  9

In [37]:
df.set_index('a')

b  c
a      
1  4  7
2  5  8
3  6  9

In [38]:
df

a  b  c
0  1  4  7
1  2  5  8
2  3  6  9

In [39]:
x = 5

In [40]:
import sys

In [41]:
sys.getsizeof(x)

28

In [42]:
type(x)

int

In [45]:
arr = np.array([5])
arr.nbytes

8

In [59]:
x = np.int64(5)
x.dtype

dtype('int64')

In [60]:
x.itemsize

8

In [61]:
sys.getsizeof(x)

32

In [71]:
arr = np.array([1.0,2.03,3], dtype=float)
arr

array([1.  , 2.03, 3.  ])

In [76]:
a = np.arange(5)
a + 20

array([20, 21, 22, 23, 24])

In [80]:
import random
a = np.random.randint(100, size=(3,3))
a

array([[55, 76, 35],
       [25, 92, 94],
       [45, 31, 76]])

In [81]:
a > 50

array([[ True,  True, False],
       [False,  True,  True],
       [False, False,  True]])

In [93]:
np.sum(a>50)

5

In [101]:
a[a>50]

array([55, 76, 92, 94, 76])

In [146]:
l = list(range(100000))

In [147]:
a = np.arange(100000)

In [148]:
%time np.sum(a**2)

CPU times: user 676 µs, sys: 261 µs, total: 937 µs
Wall time: 715 µs


333328333350000

In [177]:
%time sum([i**2 for i in l])

CPU times: user 9.55 ms, sys: 3.34 ms, total: 12.9 ms
Wall time: 15.5 ms


333328333350000

In [178]:
df2 = pd.Series(
    [100,75,50,25],
    index = ['First', 'Second', 'Third', 'Fourth']
)

In [213]:
print(df2)

First     100
Second     75
Third      50
Fourth     25
dtype: int64


In [201]:
df3 = pd.DataFrame({
    'age': [20,22,21,25],
    'name': ['Isaac', 'Q', 'Aya', 'Kay']
    },
    index=['First', 'Second', 'Third', 'Fourth']
)

In [202]:
df3

age   name
First    20  Isaac
Second   22      Q
Third    21    Aya
Fourth   25    Kay

In [203]:
df3['age'], df3['name'] = df3['name'].copy(), df3['age'].copy()

In [212]:
col1_name = 'age'
col2_name = 'name'

df3.columns = [col2_name
               if col == col1_name 
               else col1_name 
               if col == col2_name 
               else col 
               for col in df3.columns]

In [210]:
df3

name  age
First   Isaac   20
Second      Q   22
Third     Aya   21
Fourth    Kay   25

In [232]:

a = np.random.uniform(0,100, size=(10))
a

array([42.28741067, 86.80944861, 59.42677227, 14.45469256, 75.87347068,
       62.22035377, 66.29382145,  9.20580003, 47.4719831 , 46.87385201])

In [234]:
b = pd.Series(a)
b.name = 'random floats'
b

0    42.287411
1    86.809449
2    59.426772
3    14.454693
4    75.873471
5    62.220354
6    66.293821
7     9.205800
8    47.471983
9    46.873852
Name: random floats, dtype: float64

In [236]:
b.index = ['United States', 'United Kingdom', 'Japan', 'China', 'India', 'Korea', 'France', 'Germany', 'Geramny', 'Russia']

In [237]:
b

United States     42.287411
United Kingdom    86.809449
Japan             59.426772
China             14.454693
India             75.873471
Korea             62.220354
France            66.293821
Germany            9.205800
Geramny           47.471983
Russia            46.873852
Name: random floats, dtype: float64

In [239]:
c = pd.Series({
    'Matt': 26,
    'Arthur': 25,
    'Roz': 26
})
c

Matt      26
Arthur    25
Roz       26
dtype: int64

In [245]:
c = pd.Series(
    [26,25,26],
    index = ['Matt', 'Arthur', 'Roz']
)
c

Matt      26
Arthur    25
Roz       26
dtype: int64

In [247]:
d = pd.DataFrame(c)
d

0
Matt    26
Arthur  25
Roz     26

In [248]:
df2 = pd.Series(
    [26,25,26],
    index = ['Matt', 'Arthur', 'Roz']
)
df2

Matt      26
Arthur    25
Roz       26
dtype: int64

In [260]:
df2 = pd.DataFrame({
    'age': [26,25,26],
    'height': ['170cm', '186cm', '191cm']}, 
    index = ['Matt', 'Arthur', 'Roz'])


In [269]:
df2

age height
Matt     26   170 
Arthur   25   186 
Roz      26   191

In [270]:
df2['height'] = df2['height'].str.replace('cm', ' ')

In [271]:
df2['height'] = pd.to_numeric(df2['height'], errors='coerce')

In [272]:
df2

age  height
Matt     26     170
Arthur   25     186
Roz      26     191